/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-02-25 02:02:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jeju.ReservationVO;
import jeju.ReservationDB;
import java.util.ArrayList;

public final class MyPageContentInquiry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jeju.ReservationDB");
    _jspx_imports_classes.add("jeju.ReservationVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 임시 아이디 세션연결 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 예약테이블로 부터 예약정보를 받아온다. -->\r\n");

	// 로그인 세션
	String id = (String)session.getAttribute("id");
	ReservationDB db = new ReservationDB();
	ArrayList<ReservationVO> list = db.read(id); //id 정보를 주면 그 id에 해당하는 예약정보를 받아온다.

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이 페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t.part { /* li태그에 대한 영역 */\r\n");
      out.write("\t\t\t\t/* margin vs padding */\r\n");
      out.write("\t\t\t\t/* margin: 바깥쪽 여백의 속성을 지정 => 쉽게 말해 박스와 박스 사이를 조절 위 오른쪽 아래 왼쪽 순으로 밀어주는 느낌 */\r\n");
      out.write("\t\t\t\t/* padding: 안쪽 여백의 속성을 지정 */\r\n");
      out.write("\t\t\t\tlist-style: none;\r\n");
      out.write("\t\t\t\tpadding: 25px;\r\n");
      out.write("\t\t\t\tbackground: #16b4f7; /* li 영역의 배경색 설정 */\r\n");
      out.write("\t\t\t\tmargin: 0px 40px 0px 0px;\r\n");
      out.write("\t\t\t\tborder-radius: 40px 80px; /* 각 li태그마다 둥글게 */\r\n");
      out.write("\t\t\t\ttext-align: center; /* 글씨를 중앙에 맞춤 */\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.a {\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#MyPagehr {\r\n");
      out.write("\t\t\t\tmargin: 0px 0px 5px -22px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#MyPageleft { /* 왼쪽부분에 해당하는 화면 */\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\twidth: 200px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#MyPageright { /* 오른쪽부분에 해당하는 화면 */\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\twidth: 700px;\r\n");
      out.write("\t\t\t\tmargin: 0px 0px 50px 0px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#MyPagecenter { /* 내용이 들어갈 영역 */\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\twidth: 790px;\r\n");
      out.write("\t\t\t\theight: 450px;\r\n");
      out.write("\t\t\t\tbackground: white;\r\n");
      out.write("\t\t\t\toverflow: auto; /* MyPagecenter영역에 overflow 기능 사용하여 초과되는게 있으면 스크롤 처리 */\r\n");
      out.write("\t\t\t\tmargin: 0px 20px 0px -20px\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#td{\r\n");
      out.write("\t\t\t\talign = \"center\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav id = \"myMain\">\r\n");
      out.write("\t\t<nav id = \"MyTop\">\r\n");
      out.write("\t\t\t<header><!-- HTML 레이아웃 중 하나인 header 부분에 메뉴를 생성 -->\r\n");
      out.write("\t<nav id = \"logo\">\t<!-- HTML 레이아웃중 하나인 nav 부분에 생성, id는 logo 로 지정해서 style.css에서 logo를 이용해 style을 만들어줌  -->\r\n");
      out.write("\t\t<a href=\"MainPage.jsp\"> <!-- 로고를 누르면 메인페이지를 갈수 있도록 하는 a 태그 생성 -->\r\n");
      out.write("\t\t\t<img src=\"pictures/MainLogo.png\" width=\"80\" height=\"80\">\t<!-- 80x80짜리 경로를 따라서 이미지를 가져옴 -->\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</nav> <!-- 로고 레이아웃 완료 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<nav id = \"menu\" ><!-- menu라는 id를 가진 레이아웃을 생성 -->\r\n");
      out.write("\t\t<table>\t<!-- 테이블 생성 -->\r\n");
      out.write("\t\t\t<tr>\t<!-- 테이블의 한줄을 생성 -->\r\n");
      out.write("\t\t\t\t<th colspan=\"4\" style=\"text-align: right; height: 41px\"> <!-- 4열이 합병되고 오른쪽 정렬, 높이가 41px인 테이블 헤더 생성 -->\r\n");
      out.write("\t\t\t\t\t");
 if( id == null) { 
      out.write(" <!-- 세션을 이용해 로그인이 되지 않고 있을 때 아래 구문을 수행 -->\r\n");
      out.write("\t\t\t\t\t\t로그인을 해주세요.\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\t<!-- 로그인이 되었을 경우 아래 구문 수행 -->\r\n");
      out.write("\t\t\t\t\t    ");
      out.print( id );
      out.write("님 환영합니다.<a href=\"Logout.jsp\">로그아웃</a>\t<!-- 로그인된 사용자의 아이디를 출력 -->\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</th><!-- 테이블 헤더 완성 -->\r\n");
      out.write("\t\t\t</tr><!-- 테이블의 한줄을 완성 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><!-- 테이블 데이터 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t<a class=\"menuLink\" href=\"MainPage.jsp\">메인페이지</a>\t<!-- 세션을 이용해 메인페이지 셀을 눌렀을때 로그인된 아이디 값을 넘겨주면서 메인페이지로 감 -->\r\n");
      out.write("\t\t\t\t</td><!-- 테이블 데이터 완성 -->\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<a class=\"menuLink\" href=\"MyPage.jsp\">마이페이지</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<a class=\"menuLink\" href=\"ServiceMain.jsp\">고객센터</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
 if( id == null) {	
      out.write(" <!-- 세션을 이용해 로그인이 되지 않았을때 로그인을 하기위해서 로그인페이지로 연결되는 데이터셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"menuLink\" href=\"Login.jsp\">로그인</a>\r\n");
      out.write("\t\t\t\t\t");
} else {
      out.write("\t<!-- 로그인이 성공 했을경우 로그아웃을 할 수 있게하는 로그아웃으로 연결되는 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"menuLink\" href=\"UserUpdate.jsp\">회원 정보</a>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table> <!-- 테이블 완성 -->\r\n");
      out.write("\t</nav><!-- menu 레이아웃 완료 -->\r\n");
      out.write("</header> <!-- 헤더 레이아웃 완료 -->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<nav id = \"MyPageContent\">\r\n");
      out.write("\t\t\t<nav id=\"Content\">\r\n");
      out.write("\t\t\t\t<div id=\"MyPageleft\">\r\n");
      out.write("\t\t\t\t\t<ul type=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"part\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- class속성은 CSS에서 내가 li태그에 해당하는 부분을 공통적으로 수정하고자 할 때 class사용 -->\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"MyPageContentInquiry.jsp\">예약조회</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"part\"><a href=\"MyPageContentBasket.jsp\">장바구니</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 예약조회를 보여주는 화면부분 -->\r\n");
      out.write("\t\t\t\t<div id=\"MyPageright\">\r\n");
      out.write("\t\t\t\t\t<p class = \"a\">예약조회</p>\r\n");
      out.write("\t\t\t\t\t<hr id = \"MyPagehr\" color = \"#16b4f7\" size = 6 style=\"width : 113%\">\r\n");
      out.write("\t\t\t\t\t<div id=\"MyPagecenter\" >\r\n");
      out.write("\t\t\t\t\t\t<!-- 위에서 디비처리를 통해 read해온 예약정보리스트를 불러오기 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- 예약정보가 들어있는 리스트 활용 -->\r\n");
      out.write("\t\t\t\t\t\t");
 for( int i = 0; i<list.size(); i++){
							ReservationVO bag = list.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 예약정보에 대한 것과 값들을 넣을 테이블 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr> <!-- tr: table row 한 행에 해당하는 테이블 -->\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">예약번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">예약자이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">예약자번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">예약일</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">결제방법</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">방정보</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">비용</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" align = \"center\">예약관리</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_num());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_id());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_tel());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_payment());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_room());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align = \"center\">");
      out.print( bag.getRes_cost());
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- form태그 안에서 여러개의 주소로 보내야 할 경우 formaction을 활용하면된다. -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 상품 수정/ 취소를 위해 버튼 생성하고 버튼을 누를 시 예약번호를 수정/취소해주는 db처리 페이지로 보내준다. -->\r\n");
      out.write("\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button name = \"upd\" value = ");
      out.print( bag.getRes_num());
      out.write(" formaction=\"ReservationUpdate.jsp\">수정</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button name = \"del\" value = ");
      out.print( bag.getRes_num());
      out.write(" formaction=\"ReservationDeleteDB.jsp\">취소</button> </td>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div><!-- div id=\"MyPageright\" 닫기 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\t\t\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
