/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-02-25 05:57:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jeju.CustomerSoundVO;
import java.util.ArrayList;
import jeju.CustomerSoundDB;
import jeju.ProductVO;
import jeju.ProductDB;

public final class ProductDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jeju.CustomerSoundDB");
    _jspx_imports_classes.add("jeju.CustomerSoundVO");
    _jspx_imports_classes.add("jeju.ProductDB");
    _jspx_imports_classes.add("jeju.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 로그인 세션
	String id = (String)session.getAttribute("id");


	// 등록된 번호를 받아서 해당 번호의 상세 정보를 보여주도록 등록번호 파라미터를 받아 저장하는 변수를 생성
	int productNum = Integer.parseInt(request.getParameter("productNum"));
	String productName = request.getParameter("productName");
	
	// 해당 등록 번호의 데이터가 들어있는 데이터 묶음(가방)을 만들어 줌
	ProductDB db = new ProductDB();
	ProductVO bag = db.read(productNum);
		

      out.write('\r');
      out.write('\n');

	// 그림을 저장을 할 때 숙박명1.jpg 이런식으로 등록이 되도록 하였습니다.
	// 같은 숙박장소의 사진을 같은 형식으로
	//		숙박명2.jpg, 숙박명3.jpg 이런식으로 저장을 두었고
	// 출력을 하기 위해서 각각 img2, img3 변수를 만들어서
	// 		숙박명1.jpg에서 1의 부분을 2, 3으로 바꾸어서 
	// 저장되어있는 사진들의 경로를 만들어 주었습니다.
	String str = bag.getProductImage();
	String img2 = str.replace("1", "2");
	String img3 = str.replace("1", "3");

      out.write("\r\n");
      out.write("\r\n");

	// ProductSummart.jsp 에서 평점을 가져오는 것과 같은 코드입니다.
	CustomerSoundDB db2 = new CustomerSoundDB();
	ArrayList<CustomerSoundVO> list = db2.list();
	int grade = 0;
	for(int i = 0; i< list.size(); i++){
		CustomerSoundVO bag2 = list.get(i);
		if(bag2.getCustomer_accommodation_name().equals(productName)){
			grade = bag2.getCustomer_grade();
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메인 페이지 테스트</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<!-- style.css와 연결 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#ButtonTable {/* 상세 정보 페이지의 본문의 맨위에 있는 숙소 수정, 숙소 삭제 등의 버튼이 들어갈 테이블의 css 설정입니다. */\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\t/* border: 1px solid black; */\r\n");
      out.write("\tpadding-left: 450px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {/* 버튼의 모양을 설정해 줍니다. */\r\n");
      out.write("\tbackground-color: blue;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ProductS { /* 호텔 사진이 저장될 테이블의 크기 설정입니다. */\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/* border: 1px solid black; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ProductDetailImage { /* 상품 요약에 있던 사진을 가장 크게 보게 하기 위해서 그 이미지가 들어갈 부분의 크기를 설정해 주었습니다. */\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 450px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header><!-- HTML 레이아웃 중 하나인 header 부분에 메뉴를 생성 -->\r\n");
      out.write("\t\t\t<nav id = \"logo\">\t<!-- HTML 레이아웃중 하나인 nav 부분에 생성, id는 logo 로 지정해서 style.css에서 logo를 이용해 style을 만들어줌  -->\r\n");
      out.write("\t\t\t\t<a href=\"MainPage.jsp\"> <!-- 로고를 누르면 메인페이지를 갈수 있도록 하는 a 태그 생성 -->\r\n");
      out.write("\t\t\t\t\t<img src=\"pictures/MainLogo.png\" width=\"80\" height=\"80\">\t<!-- 80x80짜리 경로를 따라서 이미지를 가져옴 -->\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</nav> <!-- 로고 레이아웃 완료 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<nav id = \"search\">\t<!-- search라는 id를 가진 검색부분 레이아웃을 생성 -->\r\n");
      out.write("\t\t\t\t<form><!-- 이미지를 누르면 검색을 할수 있도록 하기위해서 form 형식으로 생성, 검색 하는것은 추후 추가 예정 -->\r\n");
      out.write("\t\t\t\t\t<img id=\"SearchImage\" src=\"pictures/Search.png\" width=\"25\" height=\"25\"><!-- 검색모양 이미지 -->\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"text\" name=\"find\"> -->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</nav> <!-- 검색 레이아웃 완료 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<nav id = \"menu\" ><!-- menu라는 id를 가진 레이아웃을 생성 -->\r\n");
      out.write("\t\t\t\t<table>\t<!-- 테이블 생성 -->\r\n");
      out.write("\t\t\t\t\t<tr>\t<!-- 테이블의 한줄을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"4\" style=\"text-align: right; height: 41px\"> <!-- 4열이 합병되고 오른쪽 정렬, 높이가 41px인 테이블 헤더 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(id == null) { 
      out.write(" <!-- 세션을 이용해 로그인이 되지 않고 있을 때 아래 구문을 수행 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t로그인을 해주세요.\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\t<!-- 로그인이 되었을 경우 아래 구문 수행 -->\r\n");
      out.write("\t\t\t\t\t\t\t    ");
      out.print( id );
      out.write("님 환영합니다.<a href=\"Logout.jsp\">로그아웃</a>\t<!-- 로그인된 사용자의 아이디를 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</th><!-- 테이블 헤더 완성 -->\r\n");
      out.write("\t\t\t\t\t</tr><!-- 테이블의 한줄을 완성 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><!-- 테이블 데이터 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"MainPage.jsp\">메인페이지</a>\t<!-- 세션을 이용해 메인페이지 셀을 눌렀을때 로그인된 아이디 값을 넘겨주면서 메인페이지로 감 -->\r\n");
      out.write("\t\t\t\t\t\t</td><!-- 테이블 데이터 완성 -->\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"MyPage.jsp\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"ServiceMain.jsp\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if( id == null) {	
      out.write(" <!-- 세션을 이용해 로그인이 되지 않았을때 로그인을 하기위해서 로그인페이지로 연결되는 데이터셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"Login.jsp\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} else {
      out.write("\t<!-- 로그인이 성공 했을경우 로그아웃을 할 수 있게하는 로그아웃으로 연결되는 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"UserUpdate.jsp\">회원 정보</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table> <!-- 테이블 완성 -->\r\n");
      out.write("\t\t\t</nav><!-- menu 레이아웃 완료 -->\r\n");
      out.write("\t\t</header> <!-- 헤더 레이아웃 완료 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<nav id=\"FixedBasket\">\r\n");
      out.write("\t\t<!-- 오른쪽에 고정될 장바구니 디스플레이를 만들기위해서 FixedBasket 아이디를 가진 nav 레이아웃 생성 -->\r\n");
      out.write("\t\t<table id=\"BasketContent\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t");
 if (session.getAttribute("productlist")!=null){ 
					/* arraylist_basket.jsp에서 세션으로 설정한 productlist를 담을 새로운 리스트를 생성 */
				 	ArrayList<String> productlist1 = (ArrayList)session.getAttribute("productlist"); /* object -> arraylist */
						if(productlist1.size()<5){ /* 최근방문페이지가 5개 보다 작은경우  */
							switch(productlist1.size()) {/* switch-case문을 통해 방문페이지가 1개 2개 3개 4개 인경우 나눔 */
							case 1:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><!-- 방문한페이지주소 (링크)+ 이름으로 표현-->\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
			case 2:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근방문페이지</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
							case 3: 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
							case 4:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-4) );
      out.write(">4.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>최근 본 상품</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;}
      out.write("<!-- 스위치문 닫기 -->\r\n");
      out.write("\t\t\t<!-- if문닫기(배열리스트길이가 5보다 작은경우) -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 방문한 페이지가 5개 이상인 경우 -->\r\n");
      out.write("\t\t\t");
}else if(productlist1.size()>=5){ 
      out.write("<!-- 길이가 5이상인경우 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-4) );
      out.write(">4.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-5) );
      out.write(">5.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
      out.write("<!-- 길이가 5이상인경우 닫기 -->\r\n");
      out.write("\t\t\t<!-- 방문한 페이지가 없는 경우 기본값으로 비워둠 -->\r\n");
      out.write("\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- 테이블을 닫음 -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- 장바구니 레이아웃을 닫아줌 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<nav id=\"Content\" style=\"background: #95fceb;\">\r\n");
      out.write("\t\t<!-- 각 조원들이 넣게될 본문 레이아웃 생성 -->\r\n");
      out.write("\t\t<table id=\"ButtonTable\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width: 80%;\">\r\n");
      out.write("\t\t\t\t\t");
 if( id != null ) {
      out.write("\t<!-- 로그인이 되었을 경우 숙소를 예약, 수정, 삭제가 가능하도록 설정-->\r\n");
      out.write("\t\t\t\t\t\t<!-- 예약하기와 장바구니는 로그인한 사람 모두가 가능하여야 하기때문에 로그인만 된다면 버튼이 나오도록 해줬습니다. -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ReservationPage.jsp?res_room=");
      out.print(bag.getProductName());
      out.write("&res_cost=");
      out.print(bag.getProductPrice());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"button\">예약하기</button>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Shoppingbag.jsp?name=");
      out.print(bag.getProductName());
      out.write("&page=");
      out.print(bag.getProductNum());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"button\">장바구니</button>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t");
 if( id.equals(bag.getProductId())) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- \t등록을 할 때 숙박업소에 대한 정보와 같이  로그인을 한 아이디가 같이 저장이 됩니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t이때 비교구문을 통해서 현재 로그인 하고 있는 아이디와 저장된 아이디가 같을 경우에만 숙소 수정과 삭제를 할 수있는 버튼이 나오도록 했습니다.\r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ProductUpdate.jsp?num=");
      out.print(bag.getProductNum());
      out.write("&classification=");
      out.print(bag.getProductClassification());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"button\">숙소 수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ProductDelete.jsp?num=");
      out.print(bag.getProductNum());
      out.write("&classification=");
      out.print(bag.getProductClassification());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"button\">숙소 삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 19%;\">\r\n");
      out.write("\t\t\t\t\t<!-- 다시 요약 페이지로 돌아가기 위한 버튼 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"ProductSummary.jsp?&num=");
      out.print(bag.getProductNum());
      out.write("&classification=");
      out.print(bag.getProductClassification());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button\">뒤로가기</button>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table id=\"ProductS\"><!-- 상세 정보의 사진들을 사진이 저장되어있는 경로를 이용해서 출력 해주는 테이블-->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"ProductDetailImage\" colspan=\"2\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(bag.getProductImage());
      out.write("\" width=\"600\"></td>\t\t\t\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(img2);
      out.write("\" width=\"350\" height=\"200\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(img3);
      out.write("\" width=\"350\" height=\"200\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- 사진이 출력되어있는 테이블의 아래 왼쪽에 들어갈 상세 정보가 출력되는 구역 -->\r\n");
      out.write("\t\t<div style=\"float: left; width:50%; font-size: 20px; padding-left: 25px\">\r\n");
      out.write("\t\t\t<!-- <table style=\"border:1px solid black;\"> -->\r\n");
      out.write("\t\t\t<table style=\"width:100%; text-align: left; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t등록자 ID >> ");
      out.print(bag.getProductId());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(bag.getProductName());
      out.write("(등록번호:");
      out.print(bag.getProductNum());
      out.write(")\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>평점 >>");
      out.print( grade );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t가격 >> ");
      out.print(bag.getProductPrice());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t룸 타입 >> ");
      out.print(bag.getProductRoomType());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t주소 >> ");
      out.print(bag.getProductLocation());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 사진 테이블 아래 오른쪽에 들어갈 상세 정보가 출력되는 구영 -->\r\n");
      out.write("\t\t<div style=\"float: left; width:45%; font-size: 20px;\">\r\n");
      out.write("\t\t\t<!-- <table style=\"border:1px solid black;\"> -->\r\n");
      out.write("\t\t\t<table style=\"width:100%; text-align: left; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t공용 시설 >> ");
      out.print(bag.getProductCommon());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t객실 내부 시설 >> ");
      out.print(bag.getProductInternal());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t픽업 가능 >> ");
      out.print(bag.getProductPickup());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 숙소 정보에 대한 부분을 출력해주는 구역 -->\r\n");
      out.write("\t\t<div style=\"float: left; width:90%; font-size: 20px; font-weight: bold;  padding-left: 25px; padding-top: 25px\">\r\n");
      out.write("\t\t\t숙소 정보<br>\r\n");
      out.write("\t\t\t");
      out.print(bag.getProductInfo());
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- 본문 닫음 -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- body 닫음 -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
