/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-02-25 07:02:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jeju.CustomerSoundVO;
import jeju.CustomerSoundDB;
import jeju.ProductVO;
import jeju.ProductDB;
import java.util.ArrayList;

public final class ProductSummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jeju.CustomerSoundDB");
    _jspx_imports_classes.add("jeju.CustomerSoundVO");
    _jspx_imports_classes.add("jeju.ProductDB");
    _jspx_imports_classes.add("jeju.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 로그인 세션을 받아줌
	String id = (String)session.getAttribute("id");
	// 아이콘을 눌렀을 때 해당 숙박 분류만 사용할 수 있도록 파라미터를 넘겨 주었습니다. 이것을 받아주기 위해 선언했습니다.
	String classification = request.getParameter("classification");	
	
	// 왼쪽에 공용시설, 객실 내 시설등을 조회할때 사용
	String[] CommonList = request.getParameterValues("Common");
	String[] InternalList = request.getParameterValues("Internal");
	
	// 요약을 출력해줄때 ArrayList를 이용해서 출력을 해주었습니다.
	ProductDB db = new ProductDB();
	ArrayList<ProductVO> summaryList = db.summaryList();
	
	// 고객의 소리에 입력된 후기의 평점을 리스트를 이요해서 가져와서 상품요약에 사용되는 평점에 사용할 수 있도록 해주었습니다.
	CustomerSoundDB db2 = new CustomerSoundDB();
	ArrayList<CustomerSoundVO> list = db2.list();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>상품 요약</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"><!-- style.css와 연결 -->\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.register{/* 숙소를 등록하는 버튼 */\r\n");
      out.write("\t\t\t\tpadding: 20px 20px 20px 20px;\r\n");
      out.write("\t\t\t\twidth:120px;\r\n");
      out.write("\t\t\t\theight:25px;\t\t\t\r\n");
      out.write("\t\t\t\ttext-align: center;\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.button{/* 버튼의 스타일 설정 */\r\n");
      out.write("\t\t\t\tbackground-color: blue;\r\n");
      out.write("\t\t\t\twidth: 100px;\r\n");
      out.write("\t\t\t\theight: 40px;\r\n");
      out.write("\t\t\t\tfont-size: 18px;\r\n");
      out.write("\t\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#GoOther{/* 왼쪽에 위치한 다른 숙박 종류로 갈수 있게 해주는 부분의 css 설정 */\r\n");
      out.write("\t\t\t\tfloat:left;\t\t\t\t\r\n");
      out.write("\t\t\t\twidth:128px;\r\n");
      out.write("\t\t\t\theight:160px;\r\n");
      out.write("\t\t\t\tmargin: 50px 10px 10px 10px;\r\n");
      out.write("\t\t\t\tbackground: blue;\r\n");
      out.write("\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\tpadding-left: 20px;\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#ClaChoice{\t\t\t\t\r\n");
      out.write("\t\t\t\twidth: 80%;\r\n");
      out.write("\t\t\t\theight:95%;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tfont-size: 24px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#ClaChoice .claBlock:visited{/* 방문 햇던 링크의 의 색이 바뀌는 것을 없에주기 위해서 사용  */\r\n");
      out.write("\t\t\t\ttext-decoration:none;/* 링크의 밑줄을 없애줌 */\r\n");
      out.write("\t\t\t\tcolor: black;/* 방문후 보라색으로 바뀌는것을 방문전의 색과 동일하게 해줌 */\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#Summary{/* 상품이 요약되는 본문의 css 설정 */\r\n");
      out.write("\t\t\t\t/* float:right;\t */\r\n");
      out.write("\t\t\t\twidth:800px;\r\n");
      out.write("\t\t\t\theight:200px;\r\n");
      out.write("\t\t\t\t/* margin: 10px 10px 10px 200px; */\t\t\t\r\n");
      out.write("\t\t\t\tbackground: #16b4f7;\r\n");
      out.write("\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\ttext-align: top;\t\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\t/* display:block; */\t\r\n");
      out.write("\t\t\t\t/* padding-bottom:500px; */\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#Summary .cellBlock{ \r\n");
      out.write("\t\t\t/* 요약해서 보여주는 것이 테이블 형식으로 설정을했고, \r\n");
      out.write("\t\t\t글자뿐이 아니라 여백을 눌러도 사용할수 있도록 설정 */\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\tcolor:black;\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t\ttext-align: left;\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#Summary .cellBlock:visited{\r\n");
      out.write("\t\t\t/* 방문 햇던 링크의 의 색이 바뀌는 것을 없에주기 위해서 사용  */\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t\t/* 링크의 밑줄을 없애줌 */\r\n");
      out.write("\t\t\t\tcolor:black;\r\n");
      out.write("\t\t\t\t/* 방문후 보라색으로 바뀌는것을 방문전의 색과 동일하게 해줌 */\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#LeftSearch{ /* 요약 페이지의 왼쪽에 조건을 설정하는 부분의 위치를 조정하기 위해서 사용 */\r\n");
      out.write("\t\t\t\tpadding-bottom:500px;\r\n");
      out.write("\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header><!-- HTML 레이아웃 중 하나인 header 부분에 메뉴를 생성 -->\r\n");
      out.write("\t\t\t<nav id = \"logo\">\t<!-- HTML 레이아웃중 하나인 nav 부분에 생성, id는 logo 로 지정해서 style.css에서 logo를 이용해 style을 만들어줌  -->\r\n");
      out.write("\t\t\t\t<a href=\"MainPage.jsp\"> <!-- 로고를 누르면 메인페이지를 갈수 있도록 하는 a 태그 생성 -->\r\n");
      out.write("\t\t\t\t\t<img src=\"pictures/MainLogo.png\" width=\"80\" height=\"80\">\t<!-- 80x80짜리 경로를 따라서 이미지를 가져옴 -->\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</nav> <!-- 로고 레이아웃 완료 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<nav id = \"search\">\t<!-- search라는 id를 가진 검색부분 레이아웃을 생성 -->\r\n");
      out.write("\t\t\t\t<form><!-- 이미지를 누르면 검색을 할수 있도록 하기위해서 form 형식으로 생성, 검색 하는것은 추후 추가 예정 -->\r\n");
      out.write("\t\t\t\t\t<img id=\"SearchImage\" src=\"pictures/Search.png\" width=\"25\" height=\"25\"><!-- 검색모양 이미지 -->\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"text\" name=\"find\"> -->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</nav> <!-- 검색 레이아웃 완료 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<nav id = \"menu\" ><!-- menu라는 id를 가진 레이아웃을 생성 -->\r\n");
      out.write("\t\t\t\t<table>\t<!-- 테이블 생성 -->\r\n");
      out.write("\t\t\t\t\t<tr>\t<!-- 테이블의 한줄을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"4\" style=\"text-align: right; height: 41px\"> <!-- 4열이 합병되고 오른쪽 정렬, 높이가 41px인 테이블 헤더 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
 if( id == null) { 
      out.write(" <!-- 세션을 이용해 로그인이 되지 않고 있을 때 아래 구문을 수행 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t로그인을 해주세요.\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\t<!-- 로그인이 되었을 경우 아래 구문 수행 -->\r\n");
      out.write("\t\t\t\t\t\t\t    ");
      out.print( id );
      out.write("님 환영합니다.<a href=\"Logout.jsp\">로그아웃</a>\t<!-- 로그인된 사용자의 아이디를 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</th><!-- 테이블 헤더 완성 -->\r\n");
      out.write("\t\t\t\t\t</tr><!-- 테이블의 한줄을 완성 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><!-- 테이블 데이터 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"MainPage.jsp\">메인페이지</a>\t<!-- 세션을 이용해 메인페이지 셀을 눌렀을때 로그인된 아이디 값을 넘겨주면서 메인페이지로 감 -->\r\n");
      out.write("\t\t\t\t\t\t</td><!-- 테이블 데이터 완성 -->\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"MyPage.jsp\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"ServiceMain.jsp\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if( id == null) {	
      out.write(" <!-- 세션을 이용해 로그인이 되지 않았을때 로그인을 하기위해서 로그인페이지로 연결되는 데이터셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"Login.jsp\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} else {
      out.write("\t<!-- 로그인이 성공 했을경우 로그아웃을 할 수 있게하는 로그아웃으로 연결되는 셀을 생성 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"menuLink\" href=\"UserUpdate.jsp\">회원 정보</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table> <!-- 테이블 완성 -->\r\n");
      out.write("\t\t\t</nav><!-- menu 레이아웃 완료 -->\r\n");
      out.write("\t\t</header> <!-- 헤더 레이아웃 완료 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<nav id=\"FixedBasket\"><!-- 오른쪽에 고정될 장바구니 디스플레이를 만들기위해서 FixedBasket 아이디를 가진 nav 레이아웃 생성 -->\r\n");
      out.write("\t\t\t<table id=\"BasketContent\" style=\"width:100%\" >\t<!-- 장바구니는 아래로 쭉 나와야 하기 때문에 하나의 열을 가진  테이블을 생성-->\r\n");
      out.write("\t\t\t\t");
 if (session.getAttribute("productlist")!=null){ 
					/* arraylist_basket.jsp에서 세션으로 설정한 productlist를 담을 새로운 리스트를 생성 */
				 	ArrayList<String> productlist1 = (ArrayList)session.getAttribute("productlist"); /* object -> arraylist */
						if(productlist1.size()<5){ /* 최근방문페이지가 5개 보다 작은경우  */
							switch(productlist1.size()) {/* switch-case문을 통해 방문페이지가 1개 2개 3개 4개 인경우 나눔 */
							case 1:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><!-- 방문한페이지주소 (링크)+ 이름으로 표현-->\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
			case 2:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근방문페이지</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
							case 3: 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;
							case 4:
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-4) );
      out.write(">4.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>최근 본 상품</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
break;}
      out.write("<!-- 스위치문 닫기 -->\r\n");
      out.write("\t\t\t<!-- if문닫기(배열리스트길이가 5보다 작은경우) -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 방문한 페이지가 5개 이상인 경우 -->\r\n");
      out.write("\t\t\t");
}else if(productlist1.size()>=5){ 
      out.write("<!-- 길이가 5이상인경우 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-1) );
      out.write(">1.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-2) );
      out.write(">2.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-3) );
      out.write(">3.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-4) );
      out.write(">4.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=");
      out.print(productlist1.get(productlist1.size()-5) );
      out.write(">5.최근본상품</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
      out.write("<!-- 길이가 5이상인경우 닫기 -->\r\n");
      out.write("\t\t\t<!-- 방문한 페이지가 없는 경우 기본값으로 비워둠 -->\r\n");
      out.write("\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>최근 본 상품</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>호텔이름</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</table><!-- 테이블을 닫음 -->\r\n");
      out.write("\t\t</nav> <!-- 장바구니 레이아웃을 닫아줌 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<nav id=\"Content\"> <!-- 각 조원들이 넣게될 본문 레이아웃 생성 -->\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div id=\"LeftSearch\" style=\"float:left; width:15%; padding:5px;\">\r\n");
      out.write("\t\t\t\t<nav class = \"register\"><!-- 숙소를 등록하기 위한 버튼을 생성해주는 태그 -->\r\n");
      out.write("\t\t\t\t\t");
 if( id == null) {	
      out.write(" <!-- 로그인을 하지 않고는 숙소를 등록할 수 없도록 설정, 로그인을 하지않을경우 로그인 버튼이 생성 -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Login.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t");
} else {
      out.write("\t\t<!-- 로그인을 했을경우 로그인 버튼이 숙소등록 버튼으로 바뀜 -->\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ProductRegister.jsp?&classification=");
      out.print( classification );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button\">숙소 등록</button>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"MainPage.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button\">돌아가기</button>\r\n");
      out.write("\t\t\t\t\t</a>\t\t\t\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<nav id=\"GoOther\"><!-- 다른 숙박 종류로 바로 가게 해주는 창 -->\r\n");
      out.write("\t\t\t\t\t<table id=\"ClaChoice\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color:black;background: #16b4f7; border-radius: 30px 60px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"claBlock\" href=\"ProductSummary.jsp?classification=Hotel\">호텔</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color:black;background: #16b4f7; border-radius: 30px 60px;\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"claBlock\" href=\"ProductSummary.jsp?classification=Resort\">리조트</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color:black;background: #16b4f7; border-radius: 30px 60px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"claBlock\" href=\"ProductSummary.jsp?classification=Pension\">펜션</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color:black;background: #16b4f7; border-radius: 30px 60px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"claBlock\" href=\"ProductSummary.jsp?classification=GuestHouse\">게/하</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t<div style=\"float:left; width:80%; padding:20px;\">\t<!-- 상품이 요약되는 본문의 css 설정 -->\r\n");
      out.write("\t\t\t\t<table id=\"Summary\" style=\"border-radius: 10px;width: 98%\"><!-- 테이블 크기 설정 -->\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i < summaryList.size() ; i++){/* ArrayList에 저장된 데이터들의 수만큼 반복하는 반복문 */
						ProductVO bag2 = summaryList.get(i);/* 저장해 놓은 데이터를 출력 */
						if(bag2.getProductClassification().equals(classification)){
							/* 아이콘을 눌러서 입력받은 파라미터를 ArrayList 안에 있는 데이터와 비교해서 맞는것만 출력되도록 비교문을 설정해줌 */
							
							/* 비교되어 출력될 데이터 가방들의 데이터중에서 숙박업소의 이름을 가져와서 저장해줍니다. */
							String productName = bag2.getProductName();
							int grade = 0;	/* 고객의 소리 평점을 가져와서 저장된 변수를 선언 */
							for(int j = 0; j<list.size();j++){	/* 고객의 소리에 저장된 만큼 반복을 해주는 반복문을 생성 */
								CustomerSoundVO bag3 = list.get(j);/* 고객의 소리의 데이터를 bag3에 저장해줍니다. */
								if(bag3.getCustomer_accommodation_name().equals(productName)){
								/* 저장이 된 것들 중에서 숙박업소 이름과 요약페이지에서 가져온 숙박업소 이름이 같을 경우  아래 구문을 실행해 평점을 가져와 저장 */
									grade = bag3.getCustomer_grade();
								}
							}
							
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"400\" rowspan=\"5\"><!-- 그림이 의 크기를 설정해주기 위해서 테이블 해더의 넓이를 설정해주고, 오른쪽에 요약된 설명의 행수만큼을 병합해줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"Arraylist_basket.jsp?productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print( bag2.getProductName() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 링크를 누르면 해당 상품 번호의 파라미터를 넘겨줘서 해당 세부정보를 보여줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print( bag2.getProductImage() );
      out.write("\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 등록을 할때 저장한 이미지경로를 가져와서 그 경로에 저장된 이미지를 출력해줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"ProductDetail.jsp?productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print(bag2.getProductName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 링크를 누르면 해당 상품 번호의 파라미터를 넘겨줘서 해당 세부정보를 보여줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t등록 ID: ");
      out.print( bag2.getProductId() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"ProductDetail.jsp?productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print(bag2.getProductName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 링크를 누르면 해당 상품 번호의 파라미터를 넘겨줘서 해당 세부정보를 보여줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t상품 제목: ");
      out.print( bag2.getProductName() );
      out.write("(상품 번호: ");
      out.print( bag2.getProductNum() );
      out.write(")<br>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"ProductDetail.jsp?productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print(bag2.getProductName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 링크를 누르면 해당 상품 번호의 파라미터를 넘겨줘서 해당 세부정보를 보여줌 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t상품 평점: ");
      out.print( grade );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"ProductDetail.jsp?&productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print(bag2.getProductName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t상품 주소: ");
      out.print( bag2.getProductLocation() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cellBlock\" href=\"ProductDetail.jsp?productNum=");
      out.print( bag2.getProductNum() );
      out.write("&productName=");
      out.print(bag2.getProductName());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t상품 가격: ");
      out.print( bag2.getProductPrice() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");

							}
					}
				
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</nav> <!-- 본문 닫음 -->\r\n");
      out.write("\t</body><!-- body 닫음 -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
